url: 'http://localhost:8080/jenkins'
user: 'admin'
password: 'password'
Projects:
  JenkinsUpdater:
    Plugin: JenkinsUpdaterMcPlugin
  PPAPO:
    Plugin: PPAPIMcPlugin
  Worldedit:
    Plugin: WorldEditMcPlugin